HTML/CSS & JavaScript capstone project - Conference page
ZuhRa-HashiMi/Capston_Project pull request #1
Opened 2022-10-19 18:38 UTC by ZuhRa-HashiMi

Use semantic HTML tags.
Apply best practices in HTML code.
Use CSS selectors correctly.
Use CSS box model.
Use Flexbox to place elements in the page.
Demonstrate ability to create UIs adaptable to different screen sizes using media queries.
Use GitHub Pages to deploy web pages.
Apply JavaScript best practices and language style guides in code.
Use JavaScript to manipulate DOM elements.
Use JavaScript events.
Use objects to store and access data.
Communicate technical concepts to other technical people.

2022-10-19 20:24 UTC, aimalamiri requested changes
Hi @ZuhRa-HashiMi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![KeepGoingGIF](https://user-images.githubusercontent.com/34779928/196796233-074f037d-83e3-47cc-9c54-0b7cc0ed4f13.gif)


## Highlights

- The pages designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️

- [ ] 1. According to the project [requirements ](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#project-documentation)you must record a video and add it's link into the pull request summary, so please make sure to add your video link into the PR summary.
- [ ] 2. Your project looks great, but you still need to work on the colors, and sizing. So kindly make sure to fix the small issues mentioned in the comments.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 20:24 UTC, aimalamiri commented on index.html
> +     </div>
This looks fantastic, but you can change its background color to make sure it's visible in front of the dark content. Kindly make sure to fix it.

![image](https://user-images.githubusercontent.com/34779928/196786251-41096748-8ca2-4644-90a4-1ced4532d91f.png)

2022-10-19 20:24 UTC, aimalamiri commented on index.html
> +            <li class="links focused"><a href="#">CC Campaign</a></li>
This part looks amazing 👌 but to improve you can increase the space between the links and increase the size of the button border. Kindly make sure to follow the original design idea.

![image](https://user-images.githubusercontent.com/34779928/196787460-c8ac7a5f-951d-4208-9d54-b366061b9d93.png)

2022-10-19 20:24 UTC, aimalamiri commented on index.html
> +          </p>
As you know it's required to follow the design guidelines, including the colors. So it's highly recommended to update your h1 color, and the `p` background` colors.

**Tip** You can use gradients for the h1 color.

![image](https://user-images.githubusercontent.com/34779928/196788529-ac8d5a3b-354e-4ebf-89ad-3e846f03c3b8.png)

2022-10-19 20:24 UTC, aimalamiri commented on index.html
> +    </div>
This looks impressive 👌But please make sure to follow the exact Behance sizing for the layout and text.

![image](https://user-images.githubusercontent.com/34779928/196789707-25d9441a-d9ef-4eb3-8ad1-7b153856776a.png)

2022-10-19 20:24 UTC, aimalamiri commented on index.html
> +        </div>
The speaker layout looks great! but you can specify the size for the images because all of the images have the same size in the Behance design, so kindly make sure to fix this.

![image](https://user-images.githubusercontent.com/34779928/196790832-2225e6d1-0bf9-4da9-ac60-11ac32cb6d0c.png)

2022-10-19 20:24 UTC, aimalamiri commented on index.html
> +        <p class="title">Partners</p>
It looks amazing 👌But kindly make sure to use the exact background color from the original design.

![image](https://user-images.githubusercontent.com/34779928/196791341-dbafd3c3-d0f3-4af7-b87b-070db9466500.png)

2022-10-19 20:24 UTC, aimalamiri commented on index.html
> +      </footer>
It looks good on mobile screens, but please follow the exact background color and text design from the original idea.

![image](https://user-images.githubusercontent.com/34779928/196791902-3da9aa32-0634-4c7f-91c3-086a5d3a8fd1.png)

2022-10-19 20:24 UTC, aimalamiri commented on about.html
> +      </p>
Good job, but it's recommended to follow the original design idea. So please kindly make sure to update it's colors and move it to the right.

2022-10-19 20:24 UTC, aimalamiri commented on about.html
> +      <div class="about-me">
The layout looks great! but please make sure to follow the original design sizing and color. 

![image](https://user-images.githubusercontent.com/34779928/196793767-2592f2ee-f93d-45bd-bbdc-e79ed0a2ae67.png)

2022-10-19 20:24 UTC, aimalamiri commented on about.html
> +        <p class="mobile">
This part looks good, but you can update the background color and sizing. So please make sure to follow the original design idea.

![image](https://user-images.githubusercontent.com/34779928/196794423-25306b94-e713-4e47-b586-9d574db31d3e.png)

2022-10-19 20:24 UTC, aimalamiri commented on README.md
> +- [Video Demo](https://zuhra-hashimi.github.io/Capston_Project/).
This is the link to the live demo. Please try recording a video using Loom and update the link.

2022-10-19 20:24 UTC, aimalamiri commented on README.md
> +# Capston_Project
It's required to give proper credit to the original idea owner, so please make sure to include the `Credits` section in your README file.

![image](https://user-images.githubusercontent.com/34779928/196795255-60e74afe-36c7-4e23-be71-03cc54598fd9.png)

2022-10-20 11:35 UTC, andgarzonmal approved these changes
Hi @ZuhRa-HashiMi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations  ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 15:45 UTC, merged